lib/dialogs/delete_confirmation.dart, lib/views/note_view.dart
closes https://github.com/keshav-space/safenotes/issues/5
=> add a confirmation prompt before deleting any notes

README.md
- fixes: https://github.com/keshav-space/safenotes/issues/2
=> add f-droid listing url

lib/dialogs/unsaved_alert.dart, lib/views/add_edit_note.dart
fixes https://github.com/keshav-space/safenotes/issues/18
=> warn before discarding the unsaved changes

lib/data/preference_and_config.dart, lib/dialogs/inactivity_msg.dart, lib/dialogs/unsaved_alert.dart, lib/main.dart, lib/models/editor_state.dart, lib/models/safenote.dart, lib/routes/route_generator.dart, lib/views/add_edit_note.dart, lib/views/auth_views/set_passphrase.dart, test/widget_test.dart
fixes https://github.com/keshav-space/safenotes/issues/27
=> Handle unsaved note during inactivity timeout

lib/data/preference_and_config.dart, lib/dialogs/select_export_folder.dart, lib/models/file_handler.dart, lib/views/home.dart
fixes https://github.com/keshav-space/safenotes/issues/9
=> let user choose destination folder for export

lib/dialogs/confirm_imort.dart, lib/dialogs/imported_file_passphrase.dart, lib/models/file_handler.dart, lib/models/import_file_parser.dart, lib/models/safenote.dart
- part fix in https://github.com/keshav-space/safenotes/commit/c0d2e35b468aa7364bd24832e8ad79eb4543e4ed
- fixes https://github.com/keshav-space/safenotes/issues/20
=> refine file import workflow

lib/authwall.dart, lib/main.dart, lib/models/session.dart, lib/routes/route_generator.dart, lib/utils/snack_message.dart, lib/views/auth_views/login.dart, lib/views/auth_views/set_passphrase.dart, lib/views/home.dart, lib/views/note_view.dart, pubspec.yaml
- fixes https://github.com/keshav-space/safenotes/issues/19
- don't use autofocus when authwall is triggered by inactivity timeout
=> redesign snackback

lib/views/home.dart, lib/widgets/note_tile.dart
@keshav-space 
Added ListTile View
=> added ListTile view

lib/data/preference_and_config.dart, lib/dialogs/change_passphrase.dart, lib/utils/snack_message.dart, lib/views/auth_views/login.dart, lib/views/auth_views/set_passphrase.dart, lib/widgets/login_button.dart, lib/widgets/note_tile.dart
fixes https://github.com/keshav-space/safenotes/issues/38
=> add brute-force protection

.metadata, lib/data/preference_and_config.dart, lib/dialogs/inactivity_logout_msg.dart, lib/views/home.dart, lib/widgets/drawer.dart
=> add grid/list view toggle

lib/utils/color.dart, lib/views/notes_color_setting.dart
- option to disable auto-color notes
- fixes https://github.com/keshav-space/safenotes/issues/7
=> Support color choosing for notes

lib/app.dart, lib/data/preference_and_config.dart, lib/dialogs/inactivity_logout_msg.dart, lib/main.dart, lib/models/app_theme.dart, lib/models/file_handler.dart, lib/routes/route_generator.dart, lib/utils/backup_shedule.dart, lib/utils/url_launcher.dart, lib/views/auth_views/login.dart, lib/views/auth_views/set_passphrase.dart, lib/views/backup_setting.dart, lib/views/change_passphrase.dart, lib/views/home.dart, lib/views/inactivity_setting.dart, lib/views/settings.dart, lib/widgets/drawer.dart, lib/widgets/note_card.dart, lib/widgets/note_tile.dart, lib/widgets/search_widget.dart, pubspec.lock, pubspec.yaml
- UI for advanced settings
- use new route transition
- new passphrase change layout
- Periodic encrypted backup to a destination folder
- fixes https://github.com/keshav-space/safenotes/issues/43
- fixes https://github.com/keshav-space/safenotes/issues/26
=> support for advanced settings

lib/data/preference_and_config.dart, lib/utils/sheduled_task.dart, lib/views/settings/backup_setting.dart
fixes https://github.com/keshav-space/safenotes/issues/58
[signed-safenotes-all.apk.zip](https://github.com/keshav-space/safenotes/files/9896757/signed-safenotes-all.apk.zip)
=> fix frozen backup

lib/views/add_edit_note.dart, lib/widgets/note_widget.dart
fixes https://github.com/keshav-space/safenotes/issues/65
=> auto scroll long text in texteditor

lib/utils/text_direction_util.dart, lib/views/note_view.dart, lib/widgets/note_card.dart, lib/widgets/note_tile.dart, lib/widgets/note_widget.dart, lib/widgets/search_widget.dart
fixes https://github.com/keshav-space/safenotes/issues/87
=> auto-detect text direction RTL/LTR

lib/data/preference_and_config.dart, lib/views/home.dart, lib/views/settings/settings.dart, lib/widgets/note_card.dart, lib/widgets/note_card_compact.dart, lib/widgets/note_tile.dart, lib/widgets/note_tile_compact.dart
fixes https://github.com/keshav-space/safenotes/issues/104
=> support compact note overview

lib/data/preference_and_config.dart, lib/models/app_theme.dart, lib/views/settings/backup_setting.dart, lib/views/settings/biometric_setting.dart, lib/views/settings/inactivity_setting.dart, lib/views/settings/language_setting.dart, lib/views/settings/notes_color_setting.dart, lib/views/settings/secure_display_setting.dart, lib/views/settings/settings.dart, lib/widgets/dark_mode.dart, lib/widgets/drawer.dart
support `Light out` mode aka Amoled black
fixes https://github.com/keshav-space/safenotes/issues/68
fixes https://github.com/keshav-space/safenotes/issues/97
Preview
:-: 
|<video src='https://user-images.githubusercontent.com/44315208/208243122-6ad16b54-6bfa-42a1-adb7-66a856cde5fb.mp4' width=180/>|
=> new dark/light theme picker

AUTHORS.md, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, lib/data/preference_and_config.dart, lib/main.dart, lib/views/settings/settings.dart, pubspec.yaml
- Bump targetSdkVersion to 33
- Enable support for  Ukrainian
- Add new Author
- Bump version for 2.3 release
=> Bump targetSdkVersion

lib/views/settings/backup_setting.dart
=> Add text button to open backup in iOS File Manager

lib/views/settings/backup_setting.dart
Fixes: https://github.com/keshav-space/safenotes/issues/195
=> Show Backup Location Text Button Only When Backup Is Enabled

lib/data/preference_and_config.dart, lib/utils/ios_style_list_tiles.dart, lib/views/settings/theme_setting.dart, lib/widgets/drawer.dart
- Resolves https://github.com/keshav-space/safenotes/issues/198
| Before  | After |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 15 - 2024-05-20 at 01 32 14](https://github.com/keshav-space/safenotes/assets/44315208/49576717-f2dc-4302-99ca-76eff2772655) | ![Simulator Screenshot - iPhone 15 - 2024-05-20 at 01 27 37](https://github.com/keshav-space/safenotes/assets/44315208/ec0aa554-10f5-4028-8c72-593215a4ea2f) |
=> Simplify dark mode settings

lib/views/settings/settings.dart, lib/widgets/footer.dart
- Resolves https://github.com/keshav-space/safenotes/issues/200
=> Show app version in settings
